//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XrayInterfaces
{
    [Serializable]
    public class Detection2DMsg : Message
    {
        public const string k_RosMessageName = "xray_interfaces/Detection2D";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg observed_at;
        public string class_id;
        public float confidence;
        public float center_x;
        public float center_y;
        public float width;
        public float height;
        public float range_estimate_m;
        public string source_frame;

        public Detection2DMsg()
        {
            this.observed_at = new BuiltinInterfaces.TimeMsg();
            this.class_id = "";
            this.confidence = 0.0f;
            this.center_x = 0.0f;
            this.center_y = 0.0f;
            this.width = 0.0f;
            this.height = 0.0f;
            this.range_estimate_m = 0.0f;
            this.source_frame = "";
        }

        public Detection2DMsg(BuiltinInterfaces.TimeMsg observed_at, string class_id, float confidence, float center_x, float center_y, float width, float height, float range_estimate_m, string source_frame)
        {
            this.observed_at = observed_at;
            this.class_id = class_id;
            this.confidence = confidence;
            this.center_x = center_x;
            this.center_y = center_y;
            this.width = width;
            this.height = height;
            this.range_estimate_m = range_estimate_m;
            this.source_frame = source_frame;
        }

        public static Detection2DMsg Deserialize(MessageDeserializer deserializer) => new Detection2DMsg(deserializer);

        private Detection2DMsg(MessageDeserializer deserializer)
        {
            this.observed_at = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.class_id);
            deserializer.Read(out this.confidence);
            deserializer.Read(out this.center_x);
            deserializer.Read(out this.center_y);
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            deserializer.Read(out this.range_estimate_m);
            deserializer.Read(out this.source_frame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.observed_at);
            serializer.Write(this.class_id);
            serializer.Write(this.confidence);
            serializer.Write(this.center_x);
            serializer.Write(this.center_y);
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.range_estimate_m);
            serializer.Write(this.source_frame);
        }

        public override string ToString()
        {
            return "Detection2DMsg: " +
            "\nobserved_at: " + observed_at.ToString() +
            "\nclass_id: " + class_id.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\ncenter_x: " + center_x.ToString() +
            "\ncenter_y: " + center_y.ToString() +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\nrange_estimate_m: " + range_estimate_m.ToString() +
            "\nsource_frame: " + source_frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
