//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XrayInterfaces
{
    [Serializable]
    public class TrackedObjectMsg : Message
    {
        public const string k_RosMessageName = "xray_interfaces/TrackedObject";
        public override string RosMessageName => k_RosMessageName;

        public string tracking_id;
        public string class_id;
        public float confidence;
        public Geometry.PoseMsg pose;
        public Geometry.Vector3Msg dimensions;
        public float[] position_covariance;
        public BuiltinInterfaces.TimeMsg last_observed;
        public bool is_persistent;
        public string source_frame;

        public TrackedObjectMsg()
        {
            this.tracking_id = "";
            this.class_id = "";
            this.confidence = 0.0f;
            this.pose = new Geometry.PoseMsg();
            this.dimensions = new Geometry.Vector3Msg();
            this.position_covariance = new float[9];
            this.last_observed = new BuiltinInterfaces.TimeMsg();
            this.is_persistent = false;
            this.source_frame = "";
        }

        public TrackedObjectMsg(string tracking_id, string class_id, float confidence, Geometry.PoseMsg pose, Geometry.Vector3Msg dimensions, float[] position_covariance, BuiltinInterfaces.TimeMsg last_observed, bool is_persistent, string source_frame)
        {
            this.tracking_id = tracking_id;
            this.class_id = class_id;
            this.confidence = confidence;
            this.pose = pose;
            this.dimensions = dimensions;
            this.position_covariance = position_covariance;
            this.last_observed = last_observed;
            this.is_persistent = is_persistent;
            this.source_frame = source_frame;
        }

        public static TrackedObjectMsg Deserialize(MessageDeserializer deserializer) => new TrackedObjectMsg(deserializer);

        private TrackedObjectMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.tracking_id);
            deserializer.Read(out this.class_id);
            deserializer.Read(out this.confidence);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.dimensions = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.position_covariance, sizeof(float), 9);
            this.last_observed = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.is_persistent);
            deserializer.Read(out this.source_frame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tracking_id);
            serializer.Write(this.class_id);
            serializer.Write(this.confidence);
            serializer.Write(this.pose);
            serializer.Write(this.dimensions);
            serializer.Write(this.position_covariance);
            serializer.Write(this.last_observed);
            serializer.Write(this.is_persistent);
            serializer.Write(this.source_frame);
        }

        public override string ToString()
        {
            return "TrackedObjectMsg: " +
            "\ntracking_id: " + tracking_id.ToString() +
            "\nclass_id: " + class_id.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\npose: " + pose.ToString() +
            "\ndimensions: " + dimensions.ToString() +
            "\nposition_covariance: " + System.String.Join(", ", position_covariance.ToList()) +
            "\nlast_observed: " + last_observed.ToString() +
            "\nis_persistent: " + is_persistent.ToString() +
            "\nsource_frame: " + source_frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
