//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XrayInterfaces
{
    [Serializable]
    public class TrackedObjectArrayMsg : Message
    {
        public const string k_RosMessageName = "xray_interfaces/TrackedObjectArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public TrackedObjectMsg[] objects;

        public TrackedObjectArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.objects = new TrackedObjectMsg[0];
        }

        public TrackedObjectArrayMsg(Std.HeaderMsg header, TrackedObjectMsg[] objects)
        {
            this.header = header;
            this.objects = objects;
        }

        public static TrackedObjectArrayMsg Deserialize(MessageDeserializer deserializer) => new TrackedObjectArrayMsg(deserializer);

        private TrackedObjectArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.objects, TrackedObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.objects);
            serializer.Write(this.objects);
        }

        public override string ToString()
        {
            return "TrackedObjectArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nobjects: " + System.String.Join(", ", objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
